### ISSUE TITLE
"Table is complete" Box does not save

### ISSUE THREAD

**Issue by Banecroft** [NeonProgrammed/JartrekMenuBuilder#16]
**"Table is complete"** does not visually stay green after logging out, and logging back in. 

Steps: 
1) click **"Table is complete"** 
2) Log out
3) Log back in 

**"Table is complete"** is no longer check marked. 

Also tried marking as completed, swapping table tabs, then logging out and back in. Same issue.

**Comment by Banecroft** [comment]
Played with it some more, seems like if you give the website a few second between each step, the **"Table is complete"** sometimes will stay check marked. However, in almost all of my attempts, when the **"Table is complete"** gets marked and then you log out it does not keep **"Table is complete"** check marked. 

Same scenario seems to be relevant in swapping tables and between **Drinks** and **Food/Snacks** as well. 

Steps:

1. Click **"Table is complete"**
2. Click another table or swap between **Drinks** and **Food/Snacks**
3. Swap back to the table that you marked **"Table is complete"**

(Not sure if this is a bug or the latency between the GUI and the backend)

**Comment by TragicallyProgrammed** [comment]
Issue was caused by a combination of the function that updates the table graphics invoking the change event on the confirmation box and the confirmation box event itself not behaving correctly. This has been corrected.
