### ISSUE TITLE
Creating New Line Issue After Deleting a Line

### ISSUE THREAD

**Issue by Banecroft** [NeonProgrammed/JartrekMenuBuilder#17]
Whenever an Item gets deleted, you cant make a new item until swapping tables and coming back. 

Steps: 
1. Have a table with 3+ lines.
 2. Create a new line.
 3. Delete any line in the current table.
 4. Fill in the new line you made. 
 5. Attempt to create another new line.

(The ONLY way I could find to fix this without swapping tables, is to: ) 

1) Click on the **"Items"** column of the line directly above the new line we created. 
2) Edit the **"Items"** column 
3) Click Tab

**Comment by TragicallyProgrammed** [comment]
This issue was caused due to a failure to set the index of each row after deleting an item. This has been corrected.
