### ISSUE TITLE
Modifiers Returning Under Same Named Category After Deletion

### ISSUE THREAD

**Issue by Banecroft** [NeonProgrammed/JartrekMenuBuilder#18]
Food Modifiers Will Return despite the whole Category being deleted if a new category with the same name is created again. 

**EXAMPLE:** Created a category named cheese, added stuff under it, but if you delete the whole category and create a new one named cheese, all the modifier options show up upon relogging. 

Steps: 
1. Navigate Food/Snacks
2. Create a table with at least one line, name the table and the item. 
3. Navigate to the **Food Modifiers** menu
4. Create a Modifier category, then create a few modifiers underneath the category. 
5. Delete the entire category
6. Create a Modifier category with the exact same name as the one previous. 
7. Log out, then back in
8. Navigate back to the category.

**Comment by Banecroft** [comment]
In addition to this, if any modifiers under the category are assigned to an item when the category is deleted, when a category with the same name is created again, the modifiers are reattached to the items they were originally.

Steps: 
1. Create a **Food Modifiers** category, then create a few modifiers underneath the category
2. Assign an item at least 1 modifier under the category that was created
3. Delete the category created above.     // _Notice the item does not display in the **Modifier Panel**._
4. Create a new category with the EXACT name of the previous one. 
5. Click on the item you assigned the modifiers originally on. 
               _Notice the item does display in the **Modifier Panel** now.
               Notice how the modifiers do not show beneath the category, but show on the item in the **Modifier Panel**_

**Comment by TragicallyProgrammed** [comment]
Changing the way the table was selecting an item seems to have corrected this issue. The table was storing the tr row of the corresponding item, it now stores the instance of the item of the corresponding row.
