### ISSUE TITLE
Food Modifiers Multiple Categories Limiting One Modifier in Second Category

### ISSUE THREAD

**Issue by Banecroft** [NeonProgrammed/JartrekMenuBuilder#19]
When creating **Food Modifier** categories, If you create one, fill in the modifiers, then when you create a second category, you cannot add more than one modifier under the second category.

Steps: 
1. Navigate to the **Food Modifier** menu
2. Create a category and fill in at least one modifier.
3. Create a second category.
4. Attempt to fill in more than one modifier under the second category.

**Comment by TragicallyProgrammed** [comment]
Issue was caused by internal array of modifier_categories had not been updated to include a modifier of id -1 upon creating a new category. This issue has been resolved.
