### ISSUE TITLE
Initial Display of Current Item Modifiers Bug

### ISSUE THREAD

**Issue by Banecroft** [NeonProgrammed/JartrekMenuBuilder#20]
Whenever you **"Add To Item"** multiple modifiers at once, duplicates of the category appear. 

Steps: 
1. Create a table under **Food/Snacks** with at least one line filled out. 
2. Navigate to the **Food Modifiers** menu
3. Create a category with 3+ modifiers underneath
4. Assign 3+ modifiers to the item at the same time. 

The duplicates don't happen if you assign one modifier at a time. Assigning a single modifier after the duplicates appear also fixes this issue.
![2022-04-21 12_39_27-Home](https://user-images.githubusercontent.com/74503362/164509320-b4f16310-815f-4c47-b688-db6833c1fb52.png)

**Comment by TragicallyProgrammed** [comment]
The bug was caused due to timing errors in the ajax request to download the items. Placing the selection function outside of the ajax request fixed the issue.
