### ISSUE TITLE
View Table as Admin Does Not Work

### ISSUE THREAD

**Issue by Banecroft** [NeonProgrammed/JartrekMenuBuilder#21]
**View Table** does not display any work done with the customer.  Regardless if the Table is marked as complete or not. 

Steps: 
1) Log into an Admin account.
2) Click on **"View Table"** for any account that has a table.

**Comment by TragicallyProgrammed** [comment]
This was a feature yet to be implemented fully into the update. The full implementation involves an event placed within the tables.js file to access the arrays of tables and modifiers necessary to manage the tables. Currently, clicking the view table button restores the HTML for datatable.html back to its original state with empty containers, and resets every array stored locally in the MenuTable function.
